#!/bin/bash

BIN_DIR=$(cd "$(dirname "$0")"; pwd)
BASE_DIR=$(dirname "$BIN_DIR")
RUN_DIR=$BASE_DIR/run

case $1 in
start)
    python $BIN_DIR/engine.py &
    ;;
stop)
    if [ ! -e $RUN_DIR/pid ]
    then
        echo "The server is not start"
        exit 1
    fi
     
    ps -ef | grep -v grep | grep auto_commit_watchdog | awk '{print $2}' | xargs kill
    pids=`cat $RUN_DIR/pid`
    count=1
    while true; 
    do
        pid=`echo $pids | awk -F ' ' '{print $'"$count"'}'` 
        echo $pid
        ((count++))
        if [ ! -n "$pid" ]
        then
            break 
        fi
        kill $pid
    done
    rm $RUN_DIR/pid 
    ;;
restart)
    $BIN_DIR/server stop
    $BIN_DIR/server start
    ;;
*)
    echo "[Error]: The argument should be start | stop | restart"
    exit 0
esac
